version: '3.9'
services:
  mongodb_container:
    image: mongo:6.0.3
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: pwp
      MONGO_INITDB_ROOT_PASSWORD: server
    restart: on-failure